server:
  port: 9999
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 50
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/belajar-mapping
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      pool-name: mapping-pool
      maximum-pool-size: 50
      max-lifetime: 600000
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:mysql://localhost:3306/belajar-mapping
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    placeholder-replacement: false